# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_brand',
            name='BrandName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='ModelName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='info_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='info_type_ebu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='info_v',
            field=models.CharField(max_length=100),
        ),
    ]
